events {}
http {
    upstream provisioner_cluster {
        server provisioner:5000;
    }

    upstream flask_cluster {
        server flask:5900;
        server flask_worker:5901;
    }

    upstream wg_cluster {
        server wg:5000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://flask_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    server {
        listen 34443 ssl;
        server_name localhost;
        ssl_certificate /etc/nginx/ssl/apiserver.crt;
        ssl_certificate_key /etc/nginx/ssl/apiserver.key;
        ssl_client_certificate /etc/nginx/ssl/ca.crt;
        ssl_verify_client on;
        ssl_protocols TLSv1.2;
        
        location / {
            proxy_pass http://flask_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /provisioner {
            proxy_pass http://provisioner_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /keychain {
            proxy_pass http://wg_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


    }

error_log /var/log/nginx/error.log debug;

}