#Default listener
listener 1883
persistence true
log_type all
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
password_file /mosquitto/config/password.txt
allow_anonymous false
acl_file /mosquitto/config/acl.txt
#Listener ssl
listener 9001
persistence true
log_type all
allow_anonymous true
cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/mosquitto.crt
keyfile /mosquitto/config/certs/mosquitto.key
tls_version tlsv1.2