FROM cowrie/cowrie
COPY ./cowrie.cfg /cowrie/cowrie-git/etc/cowrie.cfg
COPY ./userdb.txt /cowrie/cowrie-git/etc/userdb.txt
COPY ./etc/banner.txt /cowrie/cowrie-git/share/banner.txt
COPY ./etc/cmdoutput.json /cowrie/cowrie-git/src/cowrie/data/cmdoutput.json
COPY ./commands/netstat.py /cowrie/cowrie-git/cowrie/commands/netstat.py
COPY ./etc/cpuinfo /cowrie/cowrie-git/honeyfs/proc/cpuinfo