FROM cowrie/cowrie
COPY ./cowrie.cfg /cowrie/cowrie-git/etc/cowrie.cfg
COPY ./userdb.txt /cowrie/cowrie-git/etc/userdb.txt
COPY ./banner.txt /cowrie/cowrie-git/share/banner.txt
COPY ./passwd /cowrie/cowrie-git/honeyfs/etc/passwd
