services:
  mosquitto-brkr:
    image: eclipse-mosquitto
    hostname: ft-broker
    container_name: mosquitto_opcua
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto-brkr/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto-brkr/config/password.txt:/mosquitto/config/password.txt
  red-node-ui:
    image: ft/ft-ui-opcua:latest
    container_name: ft_ui_opcua
    restart: unless-stopped
    ports:
      - 1880:1880
    
